version: '3.8'

networks:
  microservices-net:
    driver: bridge

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "7000:7000"
    networks:
      - microservices-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8085:80"
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-net
